### PR TITLE
Create generator-generic-ossf-slsa3-publish.yml

### PR DESCRIPTION
**Pull request by FreeMason9224**
generator-generic-ossf-slsa3-publish.yml

### CODE REVIEW

**Review by FreeMason9224 — COMMENTED** [review]
.github/workflows/generator-generic-ossf-slsa3-publish.yml

**Review by FreeMason9224 — COMMENTED** [review]
FreeMason9224:main

**Comment by FreeMason9224** [comment]
FreeMason9224:main.patch

**Comment by julianhille** [comment]
Would you mind give a reasoning or some other idea why / what this PR actually does and what the goal is?

**Pull request closed without merging**
